version: '3.7'

services:
  spark-master:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'

  spark-worker-1:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      # - SPARK_RPC_AUTHENTICATION_ENABLED=no
      # - SPARK_RPC_ENCRYPTION_ENABLED=no
      # - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      # - SPARK_SSL_ENABLED=no
      # - SPARK_USER=spark

  spark-worker-2:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1

  spark-worker-3:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1

  spark-worker-4:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1

  spark-jupyter:
    image: jupyter/pyspark-notebook:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - '8888:8888'
      - '4040:4040'
      - '4041:4041'
    volumes:
      - type: bind
        source: ${PROJECT_DIR:-.}/pyspark_tools
        target: /home/jovyan/pyspark_tools/
